# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Memofil
email: memofil@
description: Notes pour retrouver le fil de ses idées
author: Mémofil
 # this means to ignore newlines until "baseurl:"Write an awesome description for your new site here. You can edit thisline in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://memofil.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Memofil1	
github_username:  Memofil

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

#Pour pouvoir publier des articles à date future
future: true

#Timezone
timezone: Europe/Paris



paginate: 5
paginate_path: "/blog/page:num/"


